### ISSUE TITLE
Suggestion about your RF cells

### ISSUE THREAD

**Issue by 1307053337** [patrickschulz/openPCells#12]
1. RFdesigners needs pcells with gds labels(simulation ports) in EM simulation,you can add a funcion about ports.
2. On-chip transformers are also  important cells ,you can add some in your pcell libs.

Your openPCells are excellent work , I really like your idea about independent Pcells,and I am a RFIC and EDA Designer, we can work together if you want.

**Comment by patrickschulz** [comment]
Hello and thanks for your interest and suggestions!
I've added ports to the transmission line (commit https://github.com/patrickschulz/openPCells/commit/1211450c2936a82e49a9767037e8ba86120c4e1e). I'm happy to add more cells such as transformers, I just don't have too much time right now to develop those cells. If you have any pcell code (can also be in other languages) or some example designs that you can send me that would be a great help.
